import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useSession, signIn, signOut } from "next-auth/react";
import axios from "axios";
import { useEffect, useState } from "react";

export default function Home() {
  const { data: session, status } = useSession();
  const [csrfToken, setCSRF] = useState("");

  useEffect(async () => {
    const { data } = await axios.get("/api/auth/csrf");
    console.log(data);
    setCSRF(data.csrfToken);
  }, []);

  const a = async () => {
    await axios.post("", { csrfToken: data.csrfToken });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {status === "unauthenticated" && (
        <form method="post" action="/api/auth/signin/discord">
          <input name="csrfToken" defaultValue={csrfToken} />
          <button type="submit">Sign in please</button>
        </form>
      )}

      {status === "loading" && <div>hfsuhfgiushguishd</div>}
      {status === "authenticated" && (
        <div>Signed in {JSON.stringify(session)}</div>
      )}
    </div>
  );
}
